name: Check Octez version

on:
  schedule:
    - cron: '0 0 * * *'
  # REMOVE
  push:
    branches:
      - aux/octez-version-checker

jobs:
  octez_version:
    name: Check the latest Octez release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install python-requests
        run: sudo apt-get install python3-requests
      - name: python3 octez_version.py
        run: python3 octez_version.py