name: Check Octez version

on:
  schedule:
    - cron: '0 0 * * *'
  # REMOVE
  push:
    branches:
      - aux/octez-version-checker

jobs:
  octez_version:
    name: Check the latest Octez release
    runs-on: ubuntu-latest
    steps:
      - name: Install python-requests
        run: sudo apt-get install python3-requests
      - name: make check
        run: make check