name: Tag the current Octez release


on:
  push:
    branches:
      - 'master'

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Force push tag of the current Octez release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: make release
        run: make release

      - uses: rhosys/github-action-rebuild-pull-requests@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
